name: Check manuals build

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v4
      name: Setup Gradle
      id: setup-gradle
    - name: Run gradle manualsHtmls
      run: ./gradlew -PenvIsCi=true manualHtmls
      id: gradle
